url: https://nikolaandro.github.io
baseurl: /Workouts_Page/

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Site settings
title: Nikola's Workout Collection
email: nikolazeljkoandric@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
# - name: 
#   pic: 
#   position: 
#   social:

- name: Nikola Andric
  pic: 7
  position: The Workout Collector
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nikola-andric-128597179/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nikola-andric-128597179/
  - title: github
    url: https://github.com/NikolaAndro

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
issues_repo: NikolaAndro/WorkoutPageComments.git

# exclude comments
exclude: ['jekyll-comments/']

jekyll-comments:
  apiUrl: "https://docs.google.com/spreadsheets/d/e/2PACX-1vTR147A2WRKyIoVxYEQ8LeWKuQa9X8r2kvrf_NZMRqlSfvb2TruEK-RPEWUwODR9t0xQ_qZKPCQJmUj/pubhtml"
  # [REQUIRED] the url you received from Google Apps Script step, e.g.
  # "apiUrl": "https://script.google.com/macros/s/AKfycbyTwxtrSxu...g5Guoj5KiKsPMyh4aXQ6c_/exec"
  commentsDir: "_data/comments/"
  # this is where are comments are saved, 
  # default: "_data/comments/"
  logFile: "jekyll-comments/comments.log"
  # this file will keep a list of files in which comments are updated, useful in partial builds. 
  # default: "jekyll-comments/comments.log"
  saveAsmd5: False
  # if True, the email ids in _data/comments/*.yml are saved as md5 hashes, useful if you make your _data/comments/*.yml public
  # otherwise emails are stored as it is
  # default: False
  client_id: "832575797784-sl053hh7hngp3mtrv12d7jj5mapju7pe.apps.googleusercontent.com"
  # client ID obtained from Google Sign In API
  # YOUR_CLIENT_ID.apps.googleusercontent.com
  sort: "newest_first"
  # comment sorting: "newest_first" or "oldest_first"

# adding layout defaults ( https://jekyllrb.com/docs/configuration/front-matter-defaults/ )
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"
  -
    scope:
      path: "workouts"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "page" # overrides previous default layout
