url: https://OFK-Kotroman.github.io
enforce_ssl: skolafudbalamokraagora.com
baseurl: /ofk_kotroman_mokra_gora/

# Site settings
title: Школа Фудбала ОФК Котроман
email: skolafudbalamokragora@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Никола Вучковић 
  pic: 7
  position: Тренер
  social:
    - title: instagram
      url: https://www.instagram.com/miov_mali/?utm_medium=copy_link
    - title: facebook
      url: https://www.facebook.com/nikola.vuckovic.927

- name: Александар Богдановић
  pic: 9
  position: Тренер
  social:
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100010649713713

- name: Немања Цукавац
  pic: 8
  position: Спортски Директор
  social:
    - title: instagram
      url: https://www.instagram.com/nemanja_cuki/?utm_medium=copy_link
    - title: facebook
      url: https://www.facebook.com/nemanja.cukavac

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/fk_kotroman_skola_fudbala/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
