url: https://nikolaandro.github.io
baseurl: /Workouts_Page/

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Site settings
title: Nikola's Workout Collection
email: nikolazeljkoandric@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
# - name: 
#   pic: 
#   position: 
#   social:

- name: Nikola Andric
  pic: 7
  position: The Workout Collector
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nikola-andric-128597179/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/nikola-andric-128597179/
  - title: github
    url: https://github.com/NikolaAndro

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
issues_repo: NikolaAndro/WorkoutPageComments.git
